Fixup f0e54bf Check for missing newline at end of file

diff --git a/infra/concourse/build/developer-tools/build/scripts/task_wrapper_scripts/check_eof_newline b/infra/concourse/build/developer-tools/build/scripts/task_wrapper_scripts/check_eof_newline
--- a/infra/concourse/build/developer-tools/build/scripts/task_wrapper_scripts/check_eof_newline
+++ b/infra/concourse/build/developer-tools/build/scripts/task_wrapper_scripts/check_eof_newline
@@ -9,7 +9,7 @@ rval=0
 while (( "$#" )); do
   lc="$(tail -c 1 "$1")"
   if [[ -n "${lc}" ]]; then
-    echo "No newline at end of file ${1}" >&2
+    echo "Error: No newline at end of file ${1}" >&2
     ((rval++))
   fi
   shift
